const projects=[
{id:1,name:'森序・十期',district:'北屯',area:'十期生活圈',builder:'磐石建設',score:91,trust:88,price:46.8,fair:'45.2–48.5 萬',total:'1,638 萬起',rooms:'3 房',tags:['價格合理','低公設比','品牌穩定'],reason:'成交價落在合理區間，格局方正且三面採光戶別多。'},
{id:2,name:'晴川映月',district:'南屯',area:'單元五',builder:'和築開發',score:87,trust:92,price:58.6,fair:'56.5–59.2 萬',total:'1,880 萬起',rooms:'2–3 房',tags:['售後佳','近公園','可談價'],reason:'近五案交屋紀錄穩定，基地鄰近公園。'},
{id:3,name:'嶼光之丘',district:'烏日',area:'高鐵特區',builder:'中岳營造',score:84,trust:81,price:43.2,fair:'41.8–44.0 萬',total:'1,498 萬起',rooms:'2–3 房',tags:['交通便利','總價友善','新案'],reason:'可達高鐵生活圈，與近期相似成交相比具競爭力。'},
{id:4,name:'日和學苑',district:'太平',area:'新光重劃區',builder:'安居建設',score:79,trust:74,price:39.9,fair:'38.2–40.5 萬',total:'1,298 萬起',rooms:'3 房',tags:['首購友善','近學區','資料待補'],reason:'三房總價控制佳，生活採買成熟。'},
{id:5,name:'樹里光廊',district:'西屯',area:'水湳經貿',builder:'磐石建設',score:76,trust:88,price:69.5,fair:'63.5–67.0 萬',total:'2,180 萬起',rooms:'2–3 房',tags:['品牌穩定','地段佳','價格偏高'],reason:'地段與建商品牌條件佳，長期自住便利性完整。'}];
const launches=[
{name:'青澄之森',district:'北屯',rooms:'2–3 房',meta:'北屯・十四期・青禾建設',status:'即將開售',date:'7/20 開放預約',first:'52–55 萬',now:'待公開',total:'1,688 萬起',chance:'首批名單登記中'},
{name:'嶼光之丘',district:'烏日',rooms:'2–3 房',meta:'烏日・高鐵特區・中岳營造',status:'剛開售',date:'開售第 12 天',first:'42–44 萬',now:'43.2 萬',total:'1,498 萬起',chance:'仍在首批價'},
{name:'沐光序',district:'太平',rooms:'2–3 房',meta:'太平・新光重劃區・沐森開發',status:'剛開售',date:'開售第 26 天',first:'38–40 萬',now:'40.6 萬',total:'1,368 萬起',chance:'首批尾聲'},
{name:'晴川映月',district:'南屯',rooms:'2–3 房',meta:'南屯・單元五・和築開發',status:'銷售中',date:'開售 4 個月',first:'55–57 萬',now:'58.6 萬',total:'1,880 萬起',chance:'可談價'}];
const builders=[['磐石建設',88,'12 案','穩定','良好','高'],['和築開發',92,'8 案','穩定','優良','高'],['中岳營造',81,'15 案','大致穩定','普通','中']];
let district='全部',room='不限',sort='score',launchTab='全部';const saved=new Set();
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function showPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+id)}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
function chipButtons(el,items,current,setter){el.innerHTML=items.map(x=>`<button class="${x===current?'active':''}" data-value="${x}">${x}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>setter(b.dataset.value))}
function filtered(){return projects.filter(p=>(district==='全部'||p.district===district)&&(room==='不限'||p.rooms.includes(room[0]))).sort((a,b)=>sort==='price'?a.price-b.price:sort==='trust'?b.trust-a.trust:b.score-a.score)}
function renderFilters(){chipButtons($('#districtFilters'),['全部','北屯','西屯','南屯','烏日','太平'],district,v=>{district=v;renderFilters();renderProjects();renderLaunch()});chipButtons($('#roomFilters'),['不限','2 房','3 房'],room,v=>{room=v;renderFilters();renderProjects();renderLaunch()});$('#matchCount').textContent=filtered().length}
function renderProjects(){const list=filtered();$('#matchCount').textContent=list.length;$('#projectListCount').textContent=list.length;$('#projectGrid').innerHTML=list.map((p,i)=>`<article class="project-card"><div class="project-top"><div><small>台中市・${p.district}區</small><h3>${p.name}</h3><small>${p.area}・${p.builder}</small></div><b class="score">${p.score}</b></div><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="price"><div><small>最新實登</small><b>${p.price} 萬／坪</b></div><div><small>合理價區間</small><b>${p.fair}</b></div></div><p><b>#${i+1} 推薦理由</b><br>${p.reason}</p><div class="card-actions"><button data-save="${p.id}" class="${saved.has(p.id)?'on':''}">${saved.has(p.id)?'✓ 已收藏':'＋ 收藏'}</button><button class="detail">查看分析 →</button></div></article>`).join('')||'<p class="note">目前沒有符合自住條件的建案，請回首頁調整區域或房數。</p>';$$('[data-save]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.save);saved.has(id)?saved.delete(id):saved.add(id);$('#savedCount').textContent=saved.size;renderProjects()})}
function renderLaunch(){chipButtons($('#launchTabs'),['全部','即將開售','剛開售','銷售中'],launchTab,v=>{launchTab=v;renderLaunch()});const list=launches.filter(x=>(launchTab==='全部'||x.status===launchTab)&&(district==='全部'||x.district===district)&&(room==='不限'||x.rooms.includes(room[0])));$('#launchList').innerHTML=list.map(x=>`<article class="launch-row"><div><h3>${x.name}</h3><small>${x.meta}・${x.date}</small></div><div><small>首批價格</small><b>${x.first}</b></div><div><small>目前價格</small><b>${x.now}</b></div><div><small>最低總價</small><b>${x.total}</b></div><span class="badge">${x.chance}</span></article>`).join('')||'<p class="note">目前沒有符合自住條件的開售建案，請回首頁調整區域或房數。</p>'}
function renderBuilders(){$('#builderRows').innerHTML=builders.map(b=>`<tr><td><b>${b[0]}</b></td><td><b class="builder-score">${b[1]}</b>/100</td><td>${b[2]}</td><td>${b[3]}</td><td>${b[4]}</td><td>${b[5]}</td></tr>`).join('')}
$('#sortSelect').onchange=e=>{sort=e.target.value;renderProjects()};renderFilters();renderProjects();renderLaunch();renderBuilders();const initial=location.hash.slice(1);if(['home','launch','projects','builders'].includes(initial))showPage(initial);
