const projects=window.GOVERNMENT_PROJECTS||[];
const launches=window.GOVERNMENT_LAUNCHES||[];
const builders=window.GOVERNMENT_BUILDERS||[];
let district='全部',room='不限',sort='score',launchTab='全部',launchOrder='最新備查',currentPage=1;const pageSize=12,saved=new Set(),expanded=new Set();
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function showPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+id)}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
function chipButtons(el,items,current,setter){el.innerHTML=items.map(x=>`<button class="${x===current?'active':''}" data-value="${x}">${x}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>setter(b.dataset.value))}
function filtered(){return projects.filter(p=>(district==='全部'||p.district===district)&&(room==='不限'||p.rooms.includes(room[0]))).sort((a,b)=>sort==='price'?a.price-b.price:sort==='deal'?b.dealScore-a.dealScore:b.score-a.score)}
function renderFilters(){chipButtons($('#districtFilters'),['全部','北屯','西屯','南屯','烏日','太平'],district,v=>{district=v;currentPage=1;renderAll()});chipButtons($('#roomFilters'),['不限','2 房','3 房'],room,v=>{room=v;currentPage=1;renderAll()});$('#matchCount').textContent=filtered().length}
function transactionRows(p){return `<div class="transaction-list"><div class="transaction-row transaction-head"><span>日期</span><span>房數</span><span>坪數</span><span>單價</span><span>總價</span><span>車位</span></div>${p.transactions.map(t=>`<div class="transaction-row"><span>${t.date}</span><span>${t.rooms} 房</span><span>${t.area} 坪</span><span>${t.unit} 萬/坪</span><span>${t.total.toLocaleString()} 萬</span><span>${t.parking?t.parking+' 萬':'未登載'}</span></div>`).join('')}</div>`}
function renderProjects(){const all=filtered(),pages=Math.max(1,Math.ceil(all.length/pageSize)),list=all.slice((currentPage-1)*pageSize,currentPage*pageSize);$('#matchCount').textContent=all.length;$('#projectListCount').textContent=all.length;$('#projectGrid').innerHTML=list.map(p=>`<article class="project-card"><div class="project-top"><div><small>台中市・${p.district}區</small><h3>${p.name}</h3><small>${p.area}・${p.builder}</small></div><b class="score">${p.score} 筆</b></div><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="deal-signal ${p.dealLevel}"><b>${p.dealLabel}</b><span>機會分 ${p.dealScore}・比區域中位數 ${p.priceDiff>0?'+':''}${p.priceDiff}%</span></div><div class="price"><div><small>實登中位數</small><b>${p.price} 萬／坪</b></div><div><small>已揭露區間</small><b>${p.fairLow}–${p.fairHigh} 萬</b></div></div><p><b>政府資料摘要</b><br>${p.reason}</p><div class="source-badges"><span>政府確認：成交與價格</span><span>網站計算：機會分</span><span>待查證：建案名稱</span></div><div class="card-actions"><button data-save="${p.id}" class="${saved.has(p.id)?'on':''}">${saved.has(p.id)?'✓ 追蹤中':'＋ 加入追蹤'}</button><button data-expand="${p.id}" class="detail">${expanded.has(p.id)?'收合交易':'展開交易明細 →'}</button></div>${expanded.has(p.id)?transactionRows(p):''}</article>`).join('')||'<p class="note">目前沒有符合自住條件的政府揭露資料。</p>';$('#pagination').innerHTML=all.length?`<button id="prevPage" ${currentPage===1?'disabled':''}>上一頁</button><span>第 ${currentPage}／${pages} 頁</span><button id="nextPage" ${currentPage===pages?'disabled':''}>下一頁</button>`:'';$('#prevPage')&&($('#prevPage').onclick=()=>{currentPage--;renderProjects();scrollTo({top:0,behavior:'smooth'})});$('#nextPage')&&($('#nextPage').onclick=()=>{currentPage++;renderProjects();scrollTo({top:0,behavior:'smooth'})});$$('[data-save]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.save);saved.has(id)?saved.delete(id):saved.add(id);$('#savedCount').textContent=saved.size;renderProjects()});$$('[data-expand]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.expand);expanded.has(id)?expanded.delete(id):expanded.add(id);renderProjects()})}
function renderLaunch(){chipButtons($('#launchTabs'),['全部','尚未開售','銷售中','銷售中（至完銷）','銷售期間已結束','狀態未明'],launchTab,v=>{launchTab=v;renderLaunch()});const list=launches.filter(x=>(launchTab==='全部'||x.status===launchTab)&&(district==='全部'||x.district===district)).sort((a,b)=>launchOrder==='每坪平均低到高'?(a.avgPrice??9999)-(b.avgPrice??9999):launchOrder==='每坪平均高到低'?(b.avgPrice??-1)-(a.avgPrice??-1):b.filingDate.localeCompare(a.filingDate));$('#launchList').innerHTML=list.map(x=>`<article class="launch-row"><div><h3>${x.name}</h3><small>${x.district}・${x.street}</small></div><div><small>銷售狀態</small><span class="badge">${x.status}</span></div><div><small>每坪平均</small><b>${x.avgPrice?x.avgPrice+' 萬':'尚無可配對實登'}</b><small>${x.matchCount?x.matchCount+' 筆交易平均':'政府實價尚未配對'}</small></div><div><small>申報日期</small><b>${x.filingDate}</b></div><div><small>起造人</small><b>${x.builder}</b></div><div><small>銷售期間</small><span>${x.salesPeriod}</span></div></article>`).join('')||'<p class="note">此分類目前沒有符合條件的政府備查建案。</p>'}
function renderBuilders(){$('#builderRows').innerHTML=builders.slice(0,30).map(b=>`<tr><td><b>${b.name}</b><small>${b.source}</small></td><td><i class="risk-light ${b.risk}"></i>${b.label}</td><td>${b.filingCount} 案</td><td>${b.activeCount} 案</td><td>${b.endedCount} 案</td><td>${b.clarity}%</td></tr>`).join('')}
function renderAll(){renderFilters();renderProjects();renderLaunch()}
$('#sortSelect').onchange=e=>{sort=e.target.value;currentPage=1;renderProjects()};$('#launchSort').onchange=e=>{launchOrder=e.target.value;renderLaunch()};renderAll();renderBuilders();if(window.DATA_META){$('#projectStat').textContent=window.DATA_META.projectCount;$('#transactionStat').textContent=window.DATA_META.transactionCount;const note=document.createElement('p');note.className='data-updated';note.textContent=`政府資料最後更新：${window.DATA_META.updatedAt}・${window.DATA_META.projectCount} 個本期建案・${window.DATA_META.transactionCount} 筆交易・${window.DATA_META.launchCount} 筆備查`;document.querySelector('footer').before(note)}const initial=location.hash.slice(1);if(['home','launch','projects','builders'].includes(initial))showPage(initial);
