const projects=window.GOVERNMENT_PROJECTS||[];
const launches=[...projects].sort((a,b)=>b.latest.localeCompare(a.latest)).slice(0,30).map(p=>({name:p.name,district:p.district,rooms:p.rooms,meta:`${p.district}・臺中市政府地政局`,status:'近期揭露',date:`最新交易 ${p.latest}`,first:'政府未提供',now:`${p.price} 萬`,total:p.total,chance:`已揭露 ${p.score} 筆`}));
const builders=[['經濟部商工登記','不評分','公司狀態','負責人／資本額','官方查詢','高'],['臺中市建築執照','不評分','建照／使照','起造人／承造人','官方資料','高'],['司法院裁判書','不評分','裁判紀錄','需排除同名','官方查詢','高']];
let district='全部',room='不限',sort='score',launchTab='全部',currentPage=1;const pageSize=12,saved=new Set(),expanded=new Set();
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function showPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+id)}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
function chipButtons(el,items,current,setter){el.innerHTML=items.map(x=>`<button class="${x===current?'active':''}" data-value="${x}">${x}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>setter(b.dataset.value))}
function filtered(){return projects.filter(p=>(district==='全部'||p.district===district)&&(room==='不限'||p.rooms.includes(room[0]))).sort((a,b)=>sort==='price'?a.price-b.price:b.score-a.score)}
function renderFilters(){chipButtons($('#districtFilters'),['全部','北屯','西屯','南屯','烏日','太平'],district,v=>{district=v;currentPage=1;renderAll()});chipButtons($('#roomFilters'),['不限','2 房','3 房'],room,v=>{room=v;currentPage=1;renderAll()});$('#matchCount').textContent=filtered().length}
function transactionRows(p){return `<div class="transaction-list"><div class="transaction-row transaction-head"><span>日期</span><span>房數</span><span>坪數</span><span>單價</span><span>總價</span><span>車位</span></div>${p.transactions.map(t=>`<div class="transaction-row"><span>${t.date}</span><span>${t.rooms} 房</span><span>${t.area} 坪</span><span>${t.unit} 萬/坪</span><span>${t.total.toLocaleString()} 萬</span><span>${t.parking?t.parking+' 萬':'未登載'}</span></div>`).join('')}</div>`}
function renderProjects(){const all=filtered(),pages=Math.max(1,Math.ceil(all.length/pageSize)),list=all.slice((currentPage-1)*pageSize,currentPage*pageSize);$('#matchCount').textContent=all.length;$('#projectListCount').textContent=all.length;$('#projectGrid').innerHTML=list.map(p=>`<article class="project-card"><div class="project-top"><div><small>台中市・${p.district}區</small><h3>${p.name}</h3><small>${p.area}・${p.builder}</small></div><b class="score">${p.score} 筆</b></div><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="price"><div><small>實登中位數</small><b>${p.price} 萬／坪</b></div><div><small>已揭露區間</small><b>${p.fairLow}–${p.fairHigh} 萬</b></div></div><p><b>政府資料摘要</b><br>${p.reason}</p><div class="card-actions"><button data-save="${p.id}" class="${saved.has(p.id)?'on':''}">${saved.has(p.id)?'✓ 已收藏':'＋ 收藏'}</button><button data-expand="${p.id}" class="detail">${expanded.has(p.id)?'收合交易':'展開交易明細 →'}</button></div>${expanded.has(p.id)?transactionRows(p):''}</article>`).join('')||'<p class="note">目前沒有符合自住條件的政府揭露資料。</p>';$('#pagination').innerHTML=all.length?`<button id="prevPage" ${currentPage===1?'disabled':''}>上一頁</button><span>第 ${currentPage}／${pages} 頁</span><button id="nextPage" ${currentPage===pages?'disabled':''}>下一頁</button>`:'';$('#prevPage')&&($('#prevPage').onclick=()=>{currentPage--;renderProjects();scrollTo({top:0,behavior:'smooth'})});$('#nextPage')&&($('#nextPage').onclick=()=>{currentPage++;renderProjects();scrollTo({top:0,behavior:'smooth'})});$$('[data-save]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.save);saved.has(id)?saved.delete(id):saved.add(id);$('#savedCount').textContent=saved.size;renderProjects()});$$('[data-expand]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.expand);expanded.has(id)?expanded.delete(id):expanded.add(id);renderProjects()})}
function renderLaunch(){chipButtons($('#launchTabs'),['全部','近期揭露'],launchTab,v=>{launchTab=v;renderLaunch()});const list=launches.filter(x=>(launchTab==='全部'||x.status===launchTab)&&(district==='全部'||x.district===district)&&(room==='不限'||x.rooms.includes(room[0])));$('#launchList').innerHTML=list.map(x=>`<article class="launch-row"><div><h3>${x.name}</h3><small>${x.meta}・${x.date}</small></div><div><small>首批價格</small><b>${x.first}</b></div><div><small>實登中位數</small><b>${x.now}</b></div><div><small>總價中位數</small><b>${x.total}</b></div><span class="badge">${x.chance}</span></article>`).join('')||'<p class="note">目前沒有符合條件的近期政府揭露資料。</p>'}
function renderBuilders(){$('#builderRows').innerHTML=builders.map(b=>`<tr><td><b>${b[0]}</b></td><td>${b[1]}</td><td>${b[2]}</td><td>${b[3]}</td><td>${b[4]}</td><td>${b[5]}</td></tr>`).join('')}
function renderAll(){renderFilters();renderProjects();renderLaunch()}
$('#sortSelect').onchange=e=>{sort=e.target.value;currentPage=1;renderProjects()};renderAll();renderBuilders();const initial=location.hash.slice(1);if(['home','launch','projects','builders'].includes(initial))showPage(initial);
